#!/bin/sh -e
#
# UCC initramfs tools
#
# initramfs hook for UCC
#
# Copyright 2012 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

PREREQ=""

# Output pre-requisites
prereqs()
{
        echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac


. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/parted /sbin
copy_exec /sbin/partprobe /sbin
copy_exec /sbin/mkfs.ext4 /sbin
copy_exec /sbin/mkfs.ext3 /sbin
copy_exec /sbin/mkfs.ext2 /sbin
copy_exec /sbin/mkfs.vfat /sbin
copy_exec /sbin/mke2fs /sbin
copy_exec /sbin/mkswap /sbin
copy_exec /usr/bin/bc /bin
copy_exec /bin/bunzip2 /bin
copy_exec /bin/bzcat /bin
copy_exec /usr/bin/rsync /bin
copy_exec /usr/bin/md5sum /bin
copy_exec /usr/bin/diff /bin
copy_exec /usr/bin/logger /bin

# DEBUG
copy_exec /usr/bin/vi /bin
cp -a /lib/terminfo/ $DESTDIR/lib/

# DHCP
copy_exec /sbin/udhcpc /sbin/
copy_exec /sbin/ifconfig /sbin/
copy_exec /sbin/route /sbin/
cp -pr /usr/share/udhcpc "${DESTDIR}/etc/"

