#!/bin/bash
#
# UCC - session script
#
# Copyright 2012-2013 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

# force user session
if [ -e /usr/share/univention-lightdm/force-user-session ]; then
    if [ -n "$1" ]; then
		if ["$1" = "skipforce" ]; then
			echo "Session already forced"
		fi
    else
		. /usr/share/univention-lightdm/force-user-session
    fi
fi

eval "$(/usr/sbin/ucr shell)"

export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin
. /usr/share/univention-lib/all.sh

if [ -e "/var/cache/ucc/client-policy-$(hostname).txt" ]; then
	. "/var/cache/ucc/client-policy-$(hostname).txt"
fi

# check user policy for terminal server
if [ -e "/var/cache/ucc/user-policy-$USER.txt" ]; then
	usrPolAttr="univentionCorporateClientUserUccTerminalserver"
	servers=$(cat "/var/cache/ucc/user-policy-$USER.txt" | grep "$usrPolAttr" | awk -F "$usrPolAttr=" '{print $2}' | sed 's/"//g')
fi

# overwrite user policy for terminal server if ucr policy to host is present
if [ -n "$ucc_desktop" ]; then
	servers="$ucc_desktop"
fi

# scp options
scpOptions=()
scpOptions+=("-o ConnectTimeout=3")
scpOptions+=("-o StrictHostKeyChecking=no")
scpOptions+=("-o BatchMode=yes")

if echo $servers | grep -q '\b \b'; then
	# get session host
	minLoad=999999
	for server in $servers; do
		myLoad="$(ssh ${scpOptions[@]} "$USER"@"$server" univention-showload 2>/dev/null)"
		if echo "$myLoad" | rgrep -q '^[0-9]+*'; then 
			if [ -n "$myLoad" -a "$myLoad" -lt "$minLoad" ]; then
				minLoad="$myLoad"
				sessionHost="$server"
			fi
		fi
	done
else
	sessionHost="$servers"
fi

# start session
if [ -n "$sessionHost" ]; then

	# ssh options
	sshOptions=()
	sshOptions+=("-o StrictHostKeyChecking=no")
	sshOptions+=("-o BatchMode=yes")
	sshOptions+=("-o GSSAPIDelegateCredentials=yes")
	sshOptions+=("-o ServerAliveInterval=$ucc_session_remote_session_timeout")
	sshOptions+=("-o ConnectTimeout=$ucc_session_remote_connection_timeout")

	# parameter for the session script on the terminal server
	sessionOptions=()

	# copy files
	copyFiles=()

	# copy env file to terminal server
	if [ -e "$HOME/.ucc-environment" ]; then
		copyFiles+=("$HOME/.ucc-environment")
	fi

	# x11 forwarding
	if is_ucr_true 'lightdm/xserver/allowtcp'; then
		echo "using x11 forwarding"
		cookie="$(xauth list $DISPLAY | awk '{print $NF}')"
		xauth add "$(hostname):0" . $cookie	
		if [ -e "$HOME/.Xauthority" ]; then
			copyFiles+=("$HOME/.Xauthority")
		fi
		sessionOptions+=("-x11")
	# ssh x forwarding
	else
		echo "using ssh x forwarding"
		sshOptions+=("-X")
		sshOptions+=("-c")
		if [ -n "$ucc_session_remote_ssh_cipher" ]; then
			sshOptions+=("$ucc_session_remote_ssh_cipher")
		else
			sshOptions+=("arcfour128")
		fi
		if is_ucr_true 'ucc/session/remote/ssh/compression'; then
			sshOptions+=("-C")
		fi
	fi

	# start pulseaudio and copy session cookie to terminal server
	if is_ucr_true 'ucc/session/remote/disable-sound'; then
		echo "Deactivating sound output"
	else
		killall -9 pulseaudio 2>/dev/null
		rm -f "$HOME/.pulse-cookie"
		pulseConfig="/tmp/${USER}-pulse.pa"
		echo "#!/usr/bin/pulseaudio -nF" > "$pulseConfig"
		echo "load-module module-native-protocol-tcp" >> "$pulseConfig"
		echo "load-module module-alsa-sink device=hw:0" >> "$pulseConfig"
		echo "load-module module-alsa-source device=hw:0" >> "$pulseConfig"	
		pulseaudio -D --resample-method=auto --high-priority=1 -nF "$pulseConfig"
		if [ -e "$HOME/.pulse-cookie" ]; then
			copyFiles+=("$HOME/.pulse-cookie")
			sessionOptions+=("-sound")
		fi
	fi

	# copy files to terminal server
	if [ -n "$copyFiles" ]; then
		scp "${scpOptions[@]}" "${copyFiles[@]}" "$sessionHost:~"
	fi

	# start session
	ssh "${sshOptions[@]}" "$sessionHost" "$ucc_session_remote_command" "${sessionOptions[@]}"
	if [ ! $? -eq 0 ]; then
		xmessage "Could not contact terminal server ($sessionHost) or run session script ($ucc_session_remote_command)"
	fi
	killall -9 pulseaudio 2>/dev/null
else
	xmessage "Could not find a usable terminal server, check uccTerminalServer Policy"
fi

exit 0
