#!/usr/bin/python2.7
#
# Univention Corporate Client
#  helper script: creates a script to mount the nfs root
#
# Copyright 2012-2015 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

import socket
import sys
import univention.uldap
import univention.config_registry

if __name__ == '__main__':
	servers = []

	ucr = univention.config_registry.ConfigRegistry()
	ucr.load()

	print '#!/bin/sh'

	res = None
	servers = []
	dedicatedServer = None
	try:
		lo = univention.uldap.getMachineConnection(ldap_master=False)
		res = lo.search(base=ucr.get('ldap/hostdn'), attr=['univentionCorporateClientBootImage', 'univentionCorporateClientDedicatedImageServer'], unique=True, required=True)
		bootImage = res[0][1].get('univentionCorporateClientBootImage', [None])[0]
		dedicatedServer = res[0][1].get('univentionCorporateClientDedicatedImageServer', [None])[0]
		filter = '(&(objectClass=univentionCorporateClientImage)(univentionCorporateClientImageName=%s))' % bootImage
		res = lo.search(filter=filter, attr=['univentionCorporateClientImageServer'], unique=True)
	except:
		print "# Could not establish machine connection"

	if dedicatedServer:
		servers.append(dedicatedServer)
	if res:
		for server in res[0][1].get('univentionCorporateClientImageServer', []):
			servers.append(server)

	if servers:
		print '''

nfs_mount ()
{
	server="$1"
	if mount -t nfs -o nolock,ro ${server}:/var/lib/univention-client-boot/ /tmp/nfsroot; then
		return 0
	fi
	return 1
}


'''
	for server in servers:
		print '''
if nfs_mount "%(server)s"; then
	return 0
fi
''' % {'server': socket.gethostbyname(server)}

	print 'return 1'

	sys.exit(0)


