#!/usr/bin/python2.7
#
# Univention Corporate Client
#  helper script: reads the boot flags for the UCC client
#
# Copyright 2012 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

import socket
import sys
import univention.uldap
import univention.config_registry

if __name__ == '__main__':
	servers = []

	ucr = univention.config_registry.ConfigRegistry()
	ucr.load()

	res = None
	cmdline = ''
	servers = []
	try:
		lo = univention.uldap.getMachineConnection(ldap_master=False)
		res = lo.search(base=ucr.get('ldap/hostdn'), attr=['univentionCorporateClientBootVariant', 'univentionCorporateClientBootParameter'], unique=True, required=True)
		variant = res[0][1].get('univentionCorporateClientBootVariant', [])[0]
		if variant:
			cmdline += 'ucc=%s ' % variant
		parameter = res[0][1].get('univentionCorporateClientBootParameter', [])[0]
		if parameter:
			cmdline += ' %s' % parameter
	except:
		print "Could not establish machine connection"
		sys.exit(1)

	print cmdline
	sys.exit(0)


