#!/bin/bash -e
#
# Copyright 2016 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

if [ -e /var/univention-join/joined ]; then

	# check ldap/hostdn via kerberos ldap search
	uid="$(cat /etc/hostname)\$"
	ldap_hostdn="$(ucr get ldap/hostdn)"
	kinit --password-file=/etc/machine.secret "$uid"
	dn="$(ldapsearch -Q -LLL uid=$uid dn | ldapsearch-wrapper | sed -n 's/^dn: \(.*\)/\1/p')"
	kdestroy

	# update local ldap/hostdn
	if [ -n "$dn" -a "$dn" != "$ldap_hostdn" ]; then
		ucr set ldap/hostdn="$dn"
	fi

fi

exit 0
