#!/bin/sh
#
# Univention Corporate Client
#
# Bypass entropy problems with the Citrix Receiver
#
# Copyright (C) 2007-2016 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

. /usr/share/univention-lib/all.sh

eval "$(/usr/sbin/univention-config-registry shell)"

# The Citrix Receiver 11.x queried /dev/random for certain network operations
# /dev/random blocks if insufficient entropy is present, which could lead to
# stalled logins. Please see the following references:
# http://forums.citrix.com/thread.jspa?threadID=246296
# http://forums.citrix.com/thread.jspa?threadID=311959
#
# It's not clear, whether this is still needed with Citrix Receiver 12

if  [ "$citrix_linkdevrandom" =  "true" ]; then
	if [ ! -L "/dev/random" ]; then
        mv /dev/random /dev/random.old
        ln -s /dev/urandom /dev/random
	fi
fi

exit 0
