#!/bin/sh
#
# Univention Corporate Client
#   manage /run/drives/ permissions and configure short writeback intervals for
#   USB storage attached to thin clients
#
# Copy region information to user home
#
# Copyright (C) 2012-2013 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

if [ ! -d /run/drives ]; then
	mkdir -p /run/drives
fi
chmod 700 /run/drives
chown "$USER" /run/drives

ucc_thinclient_short_expire=`/usr/sbin/univention-config-registry get ucc/sysctl/dirtyexpiredcentisecs`
ucc_thinclient_short_writeback=`/usr/sbin/univention-config-registry get ucc/sysctl/dirtywritebackcentisecs`

if [ -n "$ucc_thinclient_short_expire" -a -n "$ucc_thinclient_short_writeback" ]; then
	echo $ucc_thinclient_short_expire > /proc/sys/vm/dirty_expire_centisecs
	echo $ucc_thinclient_short_writeback > /proc/sys/vm/dirty_writeback_centisecs
fi

exit 0
