#!/bin/bash 
# Univention Corporate Client
#
# Copyright 2013 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

# This script is during during session startup with root privileges to retrieve
# the LDAP policies for the user logging in

hex_decode() {
	hex="$1"
	for((i=0;i<${#hex};i+=2)); do
		printf "\x${hex:i:2}"
	done
}

. /usr/share/univention-lib/ldap.sh

eval "$(/usr/sbin/univention-config-registry shell)"

if [ -z "$ldap_hostdn" ]; then
    echo "System not joined yet, skipping policy retrieval"
    exit 0
fi

# get user and client policies
addition=$(echo "$ldap_server_addition" | sed -e "s/,/ /g")
for host in $ldap_server_name $addition; do
	if /bin/netcat -q0 -w4 $host $ldap_server_port </dev/null >/dev/null 2>&1; then
		user_dn="$(ucs_convertUID2DN "$USER")"
		univention-policy-result -s -h "$host" -D "$ldap_hostdn" \
			-y /etc/machine.secret "$user_dn" > /var/cache/ucc/user-policy-"$USER".txt
		univention-policy-result -s -h "$host" -D "$ldap_hostdn" \
			-y /etc/machine.secret "$ldap_hostdn" > /var/cache/ucc/client-policy-"$(hostname)".txt
		break
	fi
done


# create environment file
if [ -e "$HOME/.ucc-environment" ]; then
	rm $HOME/.ucc-environment
fi
if [ -e "/var/cache/ucc/user-policy-$USER.txt" ]; then
	cat "/var/cache/ucc/user-policy-$USER.txt" | while read line; do
		var="${line%%=*}"
		val="${line#*=}"
		hex="${var#univentionCorporateClientDesktopEnv_entry_hex_}"
		if [ ! "$hex" = "$var" ]; then
			envVar="$(hex_decode $hex)"
			echo "$envVar DEFAULT=$val" >> "$HOME/.ucc-environment"
			chown "$USER" "$HOME/.ucc-environment"
		fi
	done
fi

exit 0
