univention-showload usr/bin/
50univention-ucc-application-server.inst usr/lib/univention-install/
share/KDE usr/share/univention-ucc-application-server/
share/kill-process-by-display usr/share/univention-ucc-application-server/
share/univention-ucc-kde-remote-device-bookmark usr/share/univention-ucc-application-server/
autostart/univention-ucc-kde-remote-device-bookmark.desktop usr/share/autostart/
