.TH "cdpinger" "1" "20080825"
.SH "NAME" 
cdpinger \(em notifier for cd insertion and removal events
.SH "SYNOPSIS" 
.PP 
\fBcdpinger\fR <device>
.SH "DESCRIPTION" 
.PP 
\fBcdpinger\fR is a program that informs ltspfsd(1) that a cd has been inserted or removed.
This program is not intended to be run manually, but by udev scripts from the ltspfsd package installed on a thin client. 

.SH "SEE ALSO" 
.PP 
ltspfs(1), ltspfsd(1)
.SH "AUTHOR" 
.PP 
This manual page was written by Vagrant Cascadian vagrant@freegeek.org for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
