.TH "lbmount" "1" 
.SH "NAME" 
lbmount \(em mount ltspfs based filesystems to a user owned subdir in /media 
.SH "SYNOPSIS" 
.PP 
\fBlbmount\fR 
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBlbmount\fR       command. 
 
.PP 
\fBlbmount\fR is a suid wrapper that creates mountpoints in /media and bind mounts ltspfs mounted devices to there 
\fBlbmount\fR 
.SH "OPTIONS" 
.PP 
Usage: lbmount [\-\-umount] mediadir 
 
.SH "SEE ALSO" 
.PP 
ltspfs (1). ltspfsmounter (1). 
.SH "AUTHOR" 
.PP 
This manual page was written by Oliver Grawert ogra@ubuntu.com for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Tue 29 Aug 2006, 11:56 
