#!/bin/sh
#
# Univention UCC
#  update local nss informations
#
# Copyright 2012 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

. /usr/share/univention-lib/all.sh

eval "$(univention-config-registry shell)"

# if USERNAME is set and known in passwd, we don't 
# need to update the passwd/group information
if [ -n "$USERNAME" ]; then
	if [ "$USERNAME" = "root" ]; then
		exit 0
	fi
	getent passwd "$USERNAME" && exit 0
fi

# works only for join computers
if [ ! -e "/var/univention-join/joined" ]; then
	echo "system need to be joined into ucs domain"
	exit 0
fi

# copy file from first available ldap server in ldap_server_name and ldap_server_addition
addition=$(echo "$ldap_server_addition" | sed -e "s/,/ /g")
logFile="/var/log/univention/nss-update.log"
for host in $ldap_server_name $addition; do
	if /bin/netcat -q0 -w4 $host 22 </dev/null >/dev/null 2>&1; then

		for type in group passwd; do
			src="/var/cache/ucc/$type"
			dest="/var/lib/extrausers/"
			if is_ucr_true "ucc/nss/update/hostspecific"; then
				src="/var/cache/ucc/$hostname.$type"
			fi
			echo "$(date) trying to update $type from $hostname\$@$hostname.$domainname:$src" >> $logFile
			univention-scp /etc/machine.secret "$hostname"\$\@"$host:$src" "$dest" 2>>$logFile 1>>$logFile
			if [ $? -eq 0 ]; then
				echo "$(date) -> success" >> $logFile
			else
				echo "$(date) -> failed" >> $logFile
			fi
		done
	fi
done

exit 0
