#! /bin/sh
# Xstartup - run as root before session starts

PATH="$PATH:/usr/bin/X11"

/usr/sbin/univention-ucc-fetch-user-policies

if [ -e /etc/nologin ]; then
  # always display the nologin message, if possible
  if [ -s /etc/nologin ] && which xmessage > /dev/null 2>&1; then
    xmessage -file /etc/nologin -geometry 640x480
  fi
  if [ "$(id -u)" != "0" ] && \
     ! grep -qs '^ignore-nologin' /etc/kde4/kdm/kdm.options; then
    exit 1
  fi
fi

/sbin/initctl -q emit desktop-session-start DISPLAY_MANAGER=kdm USER=$USER

# NOTE: The session is aborted if the last command returns non-zero.
