.TH default.pa 5 User Manuals
.SH NAME
default.pa \- PulseAudio Sound Server Startup Script
.SH SYNOPSIS
\fB\fI~/.config/pulse/default.pa\fB

\fI/home/arun/local/pulseaudio/etc/pulse/default.pa\fB
\f1
.SH DESCRIPTION
The PulseAudio sound server interprets the file \fI~/.config/pulse/default.pa\f1 on startup, and when that file doesn't exist \fI/home/arun/local/pulseaudio/etc/pulse/default.pa\f1. It should contain directives in the PulseAudio CLI language, as documented in \fBpulse-cli-syntax(5)\f1.

The same commands can also be entered during runtime in the \fBpacmd(1)\f1 tool, allowing flexible runtime reconfiguration.
.SH AUTHORS
The PulseAudio Developers <pulseaudio-discuss (at) lists (dot) freedesktop (dot) org>; PulseAudio is available from \fBhttp://pulseaudio.org/\f1
.SH SEE ALSO
\fBpulse-cli-syntax(5)\f1, \fBpulse-daemon.conf(5)\f1, \fBpulseaudio(1)\f1, \fBpacmd(1)\f1
