.TH start-pulseaudio-kde 1 User Manuals
.SH NAME
start-pulseaudio-kde \- PulseAudio Sound Server KDE Startup Script
.SH SYNOPSIS
\fBstart-pulseaudio-kde [\fIpulseaudio options\fB]
\f1
.SH DESCRIPTION
This script starts pulseaudio (if not already running) and loads module-device-manager to use KDE routing policies.

All arguments are directly passed to pulseaudio.
.SH AUTHORS
The PulseAudio Developers <pulseaudio-discuss (at) lists (dot) freedesktop (dot) org>; PulseAudio is available from \fBhttp://pulseaudio.org/\f1
.SH SEE ALSO
\fBpulseaudio(1)\f1
