#!/bin/bash
#
# UCC TS KDE start script
#
# Copyright (C) 2013 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

eval "$(/usr/sbin/ucr shell)"

# login script
if [ -n "$client_login_script" ]; then
    if [ -x "$client_login_script" ]; then
    	echo "Running $client_login_script as user $USER" | logger
        . "$client_login_script"
    fi
fi


# kde
echo "start remote kde session for user $USER" | logger
startkde

# logout/terminate
echo "terminate remote kde session for user $USER" | logger
qdbus org.freedesktop.Akonadi.Control /ControlManager shutdown
qdbus org.kde.kuiserver /MainApplication quit
kdeinit4_shutdown
if ! test -z "$DISPLAY"; then
	. /usr/share/univention-ucc-application-server/kill-process-by-display
fi

# logout script
if [ -n "$client_logout_script" ]; then
	if [ -x "$client_logout_script" ]; then
		echo "Running $client_logout_script as user $USER" | logger
		. "$client_logout_script"
	fi
fi

exit 0
