#!/bin/bash 
# Univention Corporate Client
#
# Copyright 2013 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

# This script is during during session startup with root privileges to retrieve
# the LDAP policies for the user logging in

. /usr/share/univention-lib/ucc.sh

logfile="/var/log/univention/software-updates.log"


# This script supports software updates for both systems with and without overlayfs
# If a system with overlaysfs is booted, it is marked for read/write operation and rebooted
if LC_ALL=C mount | grep -q "on /root-ro"; then
    /usr/sbin/univention-ucc-boot-option --write --option mount --value rw
    reboot
fi

update=`get_host_policy_var univentionCorporateClientSoftwareUpdateActivate` 
if [ $update == "1" ]; then
    plymouth message --text="Installing available software updates" 

    apt-get update 2>>$logfile 1>>$logfile
    apt-get -o DPkg::Options::=--force-confold -o DPkg::Options::=--force-overwrite -o DPkg::Options::=--force-overwrite-dir -y --force-yes -u dist-upgrade 2>>$logfile 1>>$logfile
fi

remove==`get_host_policy_var univentionCorporateClientSoftwareUpdateRemoveList`
for I in $remove
do
    PKGRM=`echo $I | tr -d "="`
    apt-get --yes remove $PKGRM 2>>$logfile 1>>$logfile
done

install==`get_host_policy_var univentionCorporateClientSoftwareUpdateInstallList` 
for I in $install
do
    PKGINST=`echo $I | tr -d "="`
    apt-get -o DPkg::Options::=--force-confold -o DPkg::Options::=--force-overwrite -o DPkg::Options::=--force-overwrite-dir -y --force-yes install $PKGINST 2>>$logfile 1>>$logfile
done

# Reset flag that triggers a r/w mount for systems booted with overlayfs
/usr/sbin/univention-ucc-boot-option --write --option mount --delete

exit 0
