#!/bin/bash 
# Univention Corporate Client
#
# Copyright 2013 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

. /usr/share/univention-lib/ucc.sh

logfile="/var/log/univention/software-updates.log"

# This script supports software updates for both systems with and without overlayfs
# If a system with overlaysfs is booted, it is marked for read/write operation and rebooted

update=`get_host_policy_var univentionCorporateClientSoftwareUpdateActivate` 
if [ "1" = "$update" ]; then

    apt-get update 2>>$logfile 1>>$logfile

    new=`LANG=C apt-get dist-upgrade --dry-run | grep "packages will be [installed|upgraded]"`
    if [ -n "$new" ]; then

	# if LC_ALL=C mount | grep -q "on /root-ro"; then
	#     /usr/sbin/univention-ucc-boot-option --write --option mount --value rw
	#     reboot
	# fi

	plymouth message --text="Installing available software updates" 
	apt-get -o DPkg::Options::=--force-confold -o DPkg::Options::=--force-overwrite -o DPkg::Options::=--force-overwrite-dir -y --force-yes -u dist-upgrade 2>>$logfile 1>>$logfile
    fi
fi

# Test whether, we need to remove packages. If so, switch to r/w mode if using overlayfs

remove=`get_host_policy_var univentionCorporateClientSoftwareUpdateRemoveList`
rmneeded=0
for I in $remove
do
    PKGRM=`echo $I | tr -d "="`
    
    dpkg -l $PKGRM > /dev/null 2> /dev/null
    if [ $? -eq 1 ]; then
		rmneeded=1
    fi

done

if [ 1 -eq $rmneeded ]; then

    # if LC_ALL=C mount | grep -q "on /root-ro"; then
	# 	/usr/sbin/univention-ucc-boot-option --write --option mount --value rw
	# 	reboot
    # fi

    for I in $remove
    do
		PKGRM=`echo $I | tr -d "="`
		plymouth message --text="Removing package $PKGRM"
		apt-get --yes remove $PKGRM 2>>$logfile 1>>$logfile
    done
fi

install=`get_host_policy_var univentionCorporateClientSoftwareUpdateInstallList` 

# Test whether, we need to install packages. If so, switch to r/w mode if using overlayfs

instneeded=0
for I in $install
do
    PKGINST=`echo $I | tr -d "="`

    new=`LANG=C apt-get install --dry-run $PKGINST | grep "packages will be [installed|upgraded]"`
    if [ -n "$new" ]; then
		instneeded=1
    fi
done

if [ 1 -eq $instneeded ]; then

    # if LC_ALL=C mount | grep -q "on /root-ro"; then
	# 	/usr/sbin/univention-ucc-boot-option --write --option mount --value rw
	# 	reboot
    # fi

    for I in $install
    do
		PKGINST=`echo $I | tr -d "="`
		plymouth message --text="Installing package $PKGINST"
		apt-get -o DPkg::Options::=--force-confold -o DPkg::Options::=--force-overwrite -o DPkg::Options::=--force-overwrite-dir -y --force-yes install $PKGINST 2>>$logfile 1>>$logfile    
    done
fi

# Reset flag that triggers a r/w mount for systems booted with overlayfs
#/usr/sbin/univention-ucc-boot-option --write --option mount --delete

exit 0
