#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          libpam-systemd
# Required-Start:    mountkernfs 
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Dummy init script, required during bootstrap in a chroot
### END INIT INFO

case "$1" in
    start)
    ;;

    stop)
    ;;

    restart)
    ;;

    reload|force-reload)
    ;;

    status)
    ;;

    *)
    echo "Usage: /etc/init.d/udev {start|stop|restart|reload|force-reload|status}" >&2
    exit 1
    ;;
esac

exit 0

