#!/bin/bash
# Univention Corporate Client
#
# Copyright 2016 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

if [ "$DESKTOP_SESSION" = "UCC" ]; then
	export DESKTOP_SESSION=ubuntu
fi

ucc_xsession="$1"
if [ -e /var/cache/ucc/fixed-session-"$USER".txt ]; then
	session=`cat /var/cache/ucc/fixed-session-"$USER".txt`
	if [ "LXDE" = "$session" -a -x /usr/bin/startlxde ]; then
		ucc_xsession="/usr/bin/startlxde"
		export DESKTOP_SESSION=LXDE
	elif [ "UCC" = "$session" -a -x /usr/bin/gnome-session ]; then
		ucc_xsession="gnome-session --session=ubuntu"
		export DESKTOP_SESSION=ubuntu
	elif [ -x "/usr/share/xsessions/$session" ]; then
		ucc_xsession="/usr/share/xsessions/$session"
		export DESKTOP_SESSION="$session"
	fi
fi

if [ "$DESKTOP_SESSION" = "ubuntu" ]; then
	export XDG_CURRENT_DESKTOP="ubuntu"
fi

exec /usr/sbin/lightdm-session "$ucc_xsession"
